
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pytest

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  #- bash <(curl -s https://scripts.scantist.com/ci-travis-jar.sh)
  - bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
  #- bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --blackduck.hub.url="https://hubeval32.blackducksoftware.com" --blackduck.hub.username="ntu" --blackduck.hub.password="ntu@2018" --blackduck.hub.trust.cert=true --detect.policy.check=true
